### PR TITLE
Generated skills

### PR DESCRIPTION
**Pull request by coudrew**
mcelearr and coudrew profiles generated as new User objects from data in dataBase.js. profiles stored in users array and data() loops through this array to generate axes and values for chart. also changed the modals up to get rid of the extra lines @mcelearr pointed out a few weeks ago.

### CODE REVIEW

**Comment by mcelearr** [comment]
I'm just looking through this now (all this time later!) and I can't get this PR to work. Any chance you could talk me through it? Would be good to get this finally merged and up on gh-pages.
jsradar

**Comment by coudrew** [comment]
smells like a typo.. i'm at school right now but i'll take a look tonight :)

**Comment by mcelearr** [comment]
No hurry. I only took 4 months to review it.....

**Comment by coudrew** [comment]
it's working well here, but if you still have a cookie from an older version it may be choking on that.

**Comment by mcelearr** [comment]
Hmmn I cleared my cookies but getting the same error. I'm thinking just merge it and see what happens. Would you be willing to help debug it if it goes wrong?

**Comment by coudrew** [comment]
yup. what browser are you using?

**Pull request merged**
